## Using Numpy


In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built in methods

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.linspace(0,5,17)

array([0.    , 0.3125, 0.625 , 0.9375, 1.25  , 1.5625, 1.875 , 2.1875,
       2.5   , 2.8125, 3.125 , 3.4375, 3.75  , 4.0625, 4.375 , 4.6875,
       5.    ])

In [13]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.random.rand(2,3)

array([[0.26397669, 0.32853808, 0.7693574 ],
       [0.20089136, 0.72873373, 0.87409419]])

In [19]:
np.random.randn(2,3)

array([[-0.10177921,  1.95414623,  0.25447364],
       [-0.63293605,  0.32650826,  0.62812884]])

In [20]:
np.random.randint(1,100,15)

array([42, 69,  4,  7, 91, 15, 80,  7, 44, 56, 96, 17, 72,  2, 56])

## Reshape and Shape


In [23]:
arr = np.random.randn(24)

In [24]:
arr

array([-5.75811410e-01,  6.82835338e-01, -9.45052246e-01,  3.63759758e-01,
        1.68978141e-01,  2.84397678e-01,  2.74871994e+00, -4.17545156e-01,
       -1.94594798e+00, -6.47321597e-01,  1.03613503e-03,  1.00713910e+00,
       -1.02691076e+00,  1.14156485e+00,  1.58385457e-01, -2.42609421e+00,
       -2.39823754e-01,  3.80570126e-01, -6.73905972e-01,  9.57861014e-01,
        2.48697357e-01, -8.62144642e-01,  1.00744011e+00, -3.10252955e-01])

In [36]:
rarr=arr.reshape(3,8)
rarr

array([[-5.75811410e-01,  6.82835338e-01, -9.45052246e-01,
         3.63759758e-01,  1.68978141e-01,  2.84397678e-01,
         2.74871994e+00, -4.17545156e-01],
       [-1.94594798e+00, -6.47321597e-01,  1.03613503e-03,
         1.00713910e+00, -1.02691076e+00,  1.14156485e+00,
         1.58385457e-01, -2.42609421e+00],
       [-2.39823754e-01,  3.80570126e-01, -6.73905972e-01,
         9.57861014e-01,  2.48697357e-01, -8.62144642e-01,
         1.00744011e+00, -3.10252955e-01]])

In [31]:
rarr.shape

(3, 8)

In [32]:
rarr.min()

-2.42609420711852

In [33]:
rarr.max()

2.7487199367305846

In [34]:
rarr.sum()

-0.9194256841344286

In [35]:
rarr.argmin()

15

# NumPy Indexing and Selection

In [38]:
arr[3]

0.36375975788607634

In [39]:
rarr

array([[-5.75811410e-01,  6.82835338e-01, -9.45052246e-01,
         3.63759758e-01,  1.68978141e-01,  2.84397678e-01,
         2.74871994e+00, -4.17545156e-01],
       [-1.94594798e+00, -6.47321597e-01,  1.03613503e-03,
         1.00713910e+00, -1.02691076e+00,  1.14156485e+00,
         1.58385457e-01, -2.42609421e+00],
       [-2.39823754e-01,  3.80570126e-01, -6.73905972e-01,
         9.57861014e-01,  2.48697357e-01, -8.62144642e-01,
         1.00744011e+00, -3.10252955e-01]])

In [41]:
rarr[2][2]

-0.6739059717878646

## Fancy Indexing

In [45]:
arr2d = np.zeros((10,10))
arr_length = arr2d.shape[0]

In [46]:
for i in range(arr_length):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [47]:
arr2d[[5,6,3]]

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

## More

In [49]:
arr =np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [4]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:

1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [7]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

In [8]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [9]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [10]:
np.max(arr) #same as arr.max()

9

In [11]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [12]:
np.log(arr)

<ipython-input-12-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])